### PR TITLE
added "export download links"

### PR DESCRIPTION
**Pull request by qiyunzhu**

### CODE REVIEW

**Comment by qiyunzhu** [comment]
@kwcantrell @YimengYang
Okay I got this function done. Now will work on the about modal.

**Comment by qiyunzhu** [comment]
Added the "about" modal. It depends on a logo image, which isn't in the current branch. But if you `git pull upstream master` you will see it.

**Comment by qiyunzhu** [comment]
Optimized the hover box. Now it shows a small arrow pointing to the selected node. The appearance and behavior were tuned to allow the user to easily move cursor into the hover box. Still not perfect but is better than before.

**Comment by kwcantrell** [comment]
Nice work! The arrow also adds a nice subtle effect.

**Pull request merged**
